development: &default
  adapter: postgresql
  database: onruby_development
  min_messages: WARNING
  pool: 5
  username: postgres
  host: db
  port: 5432

test:
  <<: *default
  database: onruby_test
